import { useCallback, useEffect, useState } from 'react'
import { BookOpen, Plus, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { request } from '@/lib/conversations'
import { HTTP_URL } from '@/lib/backend-url'
import type { ConversationLibrary } from '@/lib/conversations'
import { judgmentLabels, listSubjects, studyPath, studyJson, subjectSchema, uploadSchema, sessionSchema, type StudySubject, type SubjectDraft, type StudyUpload } from '@/lib/study'
import './study.css'

const failureText = (error: unknown) => error instanceof Error ? error.message : 'Study data could not be loaded.'

function SubjectEditor({ subject, pending, onSave, onCancel }: { subject?: StudySubject; pending: boolean; onSave: (draft: SubjectDraft) => void; onCancel: () => void }) {
  const [name, setName] = useState(subject?.name ?? '')
  const [exam, setExam] = useState(subject?.exam_type ?? 'not_sure')
  const [level, setLevel] = useState(subject?.level ?? '')
  const [date, setDate] = useState(subject?.exam_date ?? '')
  const [newTopics, setNewTopics] = useState('')
  const [topics, setTopics] = useState(subject?.topics.filter(topic => topic.active).map(topic => ({ id: topic.id, name: topic.name, coverage: topic.coverage, weight: topic.weight })) ?? [])
  return <form className="study-card study-form" onSubmit={event => {
    event.preventDefault()
    const added = newTopics.split('\n').map(name => name.trim()).filter(Boolean).map(name => ({ name, coverage: '', weight: null }))
    onSave({ name: name.trim(), exam_type: exam, level, exam_date: date, topics: [...topics, ...added] })
  }}>
    <h2>{subject ? 'Edit subject and syllabus' : 'New study subject'}</h2>
    <Label htmlFor="study-name">Subject name</Label><Input id="study-name" value={name} onChange={event => setName(event.target.value)} required maxLength={200} placeholder="DBMS" />
    <div className="study-fields"><div><Label htmlFor="study-exam">Exam type</Label><select id="study-exam" value={exam} onChange={event => setExam(event.target.value)}><option value="not_sure">Not sure</option><option value="written">Written explanations</option><option value="mcq">Multiple choice</option><option value="applied">SQL / applied problems</option><option value="mixed">Mixed</option></select></div><div><Label htmlFor="study-level">Course / level (optional)</Label><Input id="study-level" value={level} onChange={event => setLevel(event.target.value)} maxLength={200} /></div><div><Label htmlFor="study-date">Exam date (optional)</Label><Input id="study-date" type="date" value={date} onChange={event => setDate(event.target.value)} /></div></div>
    {topics.map((topic, index) => <fieldset key={topic.id} className="study-topic-edit"><legend>Topic {index + 1}</legend><Label htmlFor={`topic-name-${index}`}>Topic name</Label><Input id={`topic-name-${index}`} value={topic.name} required maxLength={200} onChange={event => setTopics(previous => previous.map((item, i) => i === index ? { ...item, name: event.target.value } : item))} /><Label htmlFor={`topic-coverage-${index}`}>Coverage / learning objectives</Label><textarea id={`topic-coverage-${index}`} value={topic.coverage} maxLength={4000} onChange={event => setTopics(previous => previous.map((item, i) => i === index ? { ...item, coverage: event.target.value } : item))} /><Label htmlFor={`topic-weight-${index}`}>Exam weight % (optional)</Label><Input id={`topic-weight-${index}`} type="number" min={0} max={100} step="any" value={topic.weight ?? ''} onChange={event => setTopics(previous => previous.map((item, i) => i === index ? { ...item, weight: event.target.value === '' ? null : Number(event.target.value) } : item))} /><Button type="button" variant="ghost" onClick={() => setTopics(previous => previous.filter((_, i) => i !== index))}>Remove from active syllabus</Button></fieldset>)}
    <Label htmlFor="study-topics">Topics, one per line</Label><textarea id="study-topics" value={newTopics} onChange={event => setNewTopics(event.target.value)} placeholder="Normalization&#10;Transactions&#10;Indexing" maxLength={10000} /><p className="study-muted">You can also create the subject first and import its syllabus. Changing coverage requires reassessment; renaming preserves progress.</p>
    <div className="study-actions"><Button disabled={pending || !name.trim()} type="submit">{pending ? 'Saving…' : subject ? 'Save subject' : 'Create subject'}</Button><Button type="button" variant="ghost" disabled={pending} onClick={onCancel}>Cancel</Button></div>
  </form>
}

function UploadReview({ upload, subject, pending, onApprove }: { upload: StudyUpload; subject: StudySubject; pending: boolean; onApprove: (text: string, topicIds: string[], topics: string) => void }) {
  const [text, setText] = useState(upload.text)
  const [topicIds, setTopicIds] = useState(upload.topic_ids)
  const [topics, setTopics] = useState('')
  return <details className="study-card" open={!upload.approved}><summary>{upload.approved ? 'Approved' : 'Review required'} · {upload.name} · {upload.role}</summary><div className="study-form">
    <p className="study-muted">Compare this extraction with your original file. It is used only after approval. <a className="underline" href={`${HTTP_URL}/study/uploads/${encodeURIComponent(upload.id)}/original`} download>Download original</a></p><Label htmlFor={`review-${upload.id}`}>Extracted text for {upload.name}</Label><textarea id={`review-${upload.id}`} value={text} onChange={event => setText(event.target.value)} maxLength={50000} rows={8} />
    {upload.role === 'syllabus' ? <><Label htmlFor={`syllabus-${upload.id}`}>Reviewed topics, one per line</Label><textarea id={`syllabus-${upload.id}`} value={topics} onChange={event => setTopics(event.target.value)} placeholder="Copy only the topic names from the extracted syllabus" /><p className="study-muted">These topics are added to your active syllabus. Edit existing coverage in Edit subject.</p></> : <fieldset><legend>Reference applies to</legend><p className="study-muted">No topics selected means all topics. For established assessment, review concise excerpts: up to 2,000 characters each and 4,000 total for a topic. Longer reference context gives provisional feedback.</p>{subject.topics.filter(topic => topic.active).map(topic => <label className="study-check" key={topic.id}><input type="checkbox" checked={topicIds.includes(topic.id)} onChange={event => setTopicIds(previous => event.target.checked ? [...previous, topic.id] : previous.filter(id => id !== topic.id))} />{topic.name}</label>)}</fieldset>}
    <Button disabled={pending || !text.trim() || (upload.role === 'syllabus' && !upload.approved && !topics.trim())} onClick={() => onApprove(text, topicIds, topics)}>{upload.approved ? 'Save reviewed changes' : 'Approve reviewed content'}</Button>
  </div></details>
}

export function StudyArea({ library, connected, sessionId, onOpenConversation }: { library: ConversationLibrary; connected: boolean; sessionId: string | null; onOpenConversation: () => void }) {
  const [subjects, setSubjects] = useState<StudySubject[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(() => { try { return localStorage.getItem('outloud.study-subject') } catch { return null } })
  const [editor, setEditor] = useState<'new' | 'edit' | null>(null)
  const [pending, setPending] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [role, setRole] = useState<'syllabus' | 'reference'>('syllabus')
  const [pages, setPages] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const [reference, setReference] = useState('')
  const [deleteTarget, setDeleteTarget] = useState<{ kind: 'subject' | 'upload'; id: string; name: string } | null>(null)
  const selected = subjects.find(subject => subject.id === selectedId)
  const refresh = useCallback(async () => {
    try { const next = await listSubjects(); setSubjects(next); setSelectedId(previous => next.some(subject => subject.id === previous) ? previous : next[0]?.id ?? null); setError(null) }
    catch (error) { setError(failureText(error)) }
  }, [])
  useEffect(() => { void Promise.resolve().then(refresh); const timer = setInterval(() => { if (document.visibilityState === 'visible' && connected) void refresh() }, 15000); return () => clearInterval(timer) }, [refresh, connected])
  useEffect(() => { try { if (selectedId) localStorage.setItem('outloud.study-subject', selectedId) } catch { /* In-memory selection remains usable. */ } }, [selectedId])
  const run = async (operation: () => Promise<void>) => { if (pending) return; setPending(true); setError(null); try { await operation() } catch (error) { setError(failureText(error)) } finally { setPending(false) } }
  const start = (topicId: string) => { if (!selected) return; void run(async () => { const session = sessionSchema.parse(await request(`${studyPath(selected.id)}/topics/${encodeURIComponent(topicId)}/conversations`, { method: 'POST' })); await library.refresh(); await library.select(session.conversation_id); onOpenConversation() }) }
  return <main className="study-area" aria-label="Study">
    <header className="study-header"><div><p className="study-eyebrow">EXAM PREPARATION</p><h1><BookOpen size={24} />Study</h1><p className="study-muted">Explain what you know. Find what to revise.</p></div><div className="study-actions"><Button variant="ghost" aria-label="Refresh study progress" onClick={() => void refresh()} disabled={pending}><RefreshCw /></Button><Button onClick={() => setEditor('new')} disabled={!connected || pending}><Plus />New subject</Button></div></header>
    {error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
    {subjects.length > 0 && <nav className="study-subjects" aria-label="Study subjects">{subjects.map(subject => <Button key={subject.id} variant={subject.id === selectedId ? 'secondary' : 'ghost'} onClick={() => { setSelectedId(subject.id); setEditor(null); setDeleteTarget(null) }}>{subject.name}</Button>)}</nav>}
    {(editor || !subjects.length) && <SubjectEditor key={editor === 'edit' ? selectedId : 'new'} subject={editor === 'edit' ? selected : undefined} pending={pending || !connected} onCancel={() => setEditor(null)} onSave={draft => void run(async () => { const saved = subjectSchema.parse(await request(editor === 'edit' && selected ? studyPath(selected.id) : '/study/subjects', studyJson(editor === 'edit' ? 'PATCH' : 'POST', draft))); await refresh(); setSelectedId(saved.id); setEditor(null) })} />}
    {selected && !editor && <>
      <section className="study-card"><div className="study-header"><div><h2>{selected.name}</h2><p className="study-muted">{selected.exam_type === 'not_sure' ? 'Exam type not set' : selected.exam_type} {selected.level && `· ${selected.level}`} {selected.exam_date && `· ${selected.exam_date}`}</p></div><Button variant="outline" onClick={() => setEditor('edit')} disabled={pending || !connected}>Edit subject</Button></div>
        <div className="study-stats"><div><strong>{selected.coverage.assessed} of {selected.coverage.total} topics assessed</strong><p>Assessment coverage</p></div><div><strong>{selected.coverage.demonstrated} topics demonstrated</strong><p>Supported independent understanding</p></div></div>
        <Button onClick={() => { const next = selected.revision_order[0]; if (next) start(next) }} disabled={!connected || pending || !selected.revision_order.length}>Study next recommendation</Button>
      </section>
      <section aria-label="Topics and revision priorities" className="study-topics">{selected.revision_order.map((id, index) => { const topic = selected.topics.find(topic => topic.id === id)!; return <article key={id} className="study-card"><div className="study-header"><div><p className="study-eyebrow">REVISION PRIORITY {index + 1}</p><h3>{topic.name}</h3></div><span className={`study-judgment study-${topic.judgment}`}>{judgmentLabels[topic.judgment]}</span></div><p className="study-muted">Exam importance: {topic.weight === null ? 'Unknown' : `${topic.weight}%`}</p>{topic.needs_reassessment && <p>Reassessment needed: coverage or supporting evidence changed.</p>}{topic.assessment && <><p>{topic.assessment.feedback}</p>{topic.assessment.gaps.length > 0 && <ul>{topic.assessment.gaps.map((gap, i) => <li key={i}>{gap}</li>)}</ul>}<p className="study-muted">{topic.assessment.provisional ? 'Provisional feedback · verify before relying on it' : 'Assessed'} · {new Date(topic.assessment.created_at).toLocaleDateString()}</p></>}<Button aria-label={`Study ${topic.name}`} variant="outline" onClick={() => start(id)} disabled={!connected || pending}>Study topic</Button>{topic.history.length > 0 && <details><summary>Assessment evidence ({topic.history.length})</summary>{topic.history.map(item => <div key={item.user_message_id} className="study-evidence"><p className="study-muted">{new Date(item.created_at).toLocaleDateString()} · {item.hinted ? 'Assisted' : 'Independent'} · {item.revision === topic.revision ? 'Current coverage' : 'Earlier coverage'}</p><p><strong>Question:</strong> {item.question}</p><p><strong>Your answer:</strong> {item.answer}</p><p>{item.result.feedback}</p><Button size="sm" variant="ghost" onClick={() => void run(async () => { await library.select(item.conversation_id); onOpenConversation() })}>Open study conversation</Button></div>)}</details>}</article> })}</section>
      {selected.topics.some(topic => !topic.active) && <details className="study-card"><summary>Removed topics and historical assessments</summary>{selected.topics.filter(topic => !topic.active).map(topic => <div key={topic.id}><h3>{topic.name}</h3><p>{judgmentLabels[topic.judgment]} · {topic.history.length} saved evidence records</p>{topic.history.map(item => <p key={item.user_message_id}>{item.answer} — {item.result.feedback}</p>)}</div>)}</details>}
      <section className="study-card study-form"><h2>Syllabus and reference material</h2><p className="study-muted">Printed PDFs and clear PNG/JPEG/WebP photos or scans. Up to 8 MB and five selected PDF pages per import. Handwriting is not supported yet.</p><Label htmlFor="study-upload-role">File role</Label><select id="study-upload-role" value={role} onChange={event => setRole(event.target.value === 'syllabus' ? 'syllabus' : 'reference')}><option value="syllabus">Syllabus — defines topics</option><option value="reference">Reference — supports feedback</option></select><Label htmlFor="study-file">PDF or image</Label><Input id="study-file" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={event => setFile(event.target.files?.[0] ?? null)} /><Label htmlFor="study-pages">PDF pages (optional, comma-separated)</Label><Input id="study-pages" value={pages} onChange={event => setPages(event.target.value)} placeholder="1,2,3 — otherwise the first five pages" /><Button disabled={!file || !sessionId || pending || !connected} onClick={() => void run(async () => { if (!file || !sessionId) return; if (file.size > 8 * 1024 * 1024) throw new Error('Choose a file of at most 8 MB.'); await request(`${studyPath(selected.id)}/uploads?name=${encodeURIComponent(file.name)}&role=${role}&pages=${encodeURIComponent(pages)}`, { method: 'POST', headers: { 'Content-Type': 'application/octet-stream', 'X-Session-ID': sessionId }, body: file, signal: AbortSignal.timeout(190000) }); setFile(null); await refresh() })}>{pending ? 'Working…' : 'Extract for review'}</Button>
        <details><summary>Paste reference material instead</summary><Label htmlFor="study-reference">Reference text</Label><textarea id="study-reference" value={reference} onChange={event => setReference(event.target.value)} maxLength={50000} /><Button disabled={!reference.trim() || pending || !connected} onClick={() => void run(async () => { await request(`${studyPath(selected.id)}/references`, studyJson('POST', { name: 'Pasted reference', text: reference, topic_ids: [] })); setReference(''); await refresh() })}>Save reviewed reference</Button></details>
      </section>
      {selected.uploads.map(upload => <div key={upload.id}><UploadReview key={`${upload.id}-${upload.text}`} upload={upload} subject={selected} pending={pending || !connected} onApprove={(text, topicIds, topics) => void run(async () => { uploadSchema.parse(await request(`/study/uploads/${encodeURIComponent(upload.id)}`, studyJson('PATCH', { text, topic_ids: topicIds, topics: topics.split('\n').map(name => name.trim()).filter(Boolean).map(name => ({ name })) }))); await refresh() })} /><Button variant="ghost" disabled={pending || !connected} onClick={() => setDeleteTarget({ kind: 'upload', id: upload.id, name: upload.name })}>Remove {upload.name}</Button></div>)}
      <Button variant="ghost" disabled={pending || !connected} onClick={() => setDeleteTarget({ kind: 'subject', id: selected.id, name: selected.name })}>Delete subject</Button>
    </>}
    {deleteTarget && <section role="alertdialog" aria-labelledby="study-delete-title" aria-describedby="study-delete-description" className="study-card"><h2 id="study-delete-title">Delete {deleteTarget.name}?</h2><p id="study-delete-description">{deleteTarget.kind === 'subject' ? 'This removes its study conversations, progress, and uploaded files.' : 'Assessments that depend on this reference will need reassessment.'} This cannot be undone.</p><div className="study-actions"><Button variant="outline" onClick={() => setDeleteTarget(null)} disabled={pending}>Keep it</Button><Button variant="destructive" disabled={pending} onClick={() => void run(async () => { await request(deleteTarget.kind === 'subject' ? studyPath(deleteTarget.id) : `/study/uploads/${encodeURIComponent(deleteTarget.id)}`, { method: 'DELETE' }); setDeleteTarget(null); await library.refresh(); await refresh() })}>Confirm delete</Button></div></section>}
  </main>
}
